# Generated by Django 5.2 on 2025-12-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='Phone',
            new_name='phone',
        ),
    ]
