# Generated by Django 5.2 on 2025-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_phone_consultation_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='policy_start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
