# Generated by Django 5.2 on 2025-12-25 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='responded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
