# Generated by Django 5.2 on 2025-12-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_consultation_responded_at_consultation_responded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded')], default='pending', max_length=10),
        ),
    ]
