# Generated by Django 5.2 on 2025-12-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vaccancy_count', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('salary', models.CharField(max_length=100)),
                ('experiance', models.CharField(choices=[('Fresher', 'Fresher'), ('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5+ years', '5+ years')], default='Fresher', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='base.jobnotification')),
            ],
        ),
    ]
