# Generated by Django 5.2.8 on 2026-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_newsletter_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter_subscribers',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
