# Generated by Django 5.2 on 2025-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_jobnotification_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
