# Generated by Django 5.2.8 on 2025-12-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_jobnotification_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
