# Generated by Django 5.2 on 2026-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_newsletter_subscribers_unsubscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
