# Generated by Django 5.2 on 2025-12-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('hold', 'Hold'), ('publish', 'Publish')], default='hold', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MOD', 'mod'), ('hr', 'HR'), ('INS_ADMIN', 'Insurance_Administrator'), ('general_manager', 'General_Manager')], default='MOD', max_length=20),
        ),
    ]
