# Generated by Django 5.2 on 2025-12-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_post_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='status',
        ),
    ]
