# Generated by Django 5.2 on 2025-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotification',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='jobnotification',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
