# Generated by Django 5.2 on 2026-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_contactus_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='camp_images/')),
                ('tests_offered', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('timing', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
