# Generated by Django 5.2 on 2026-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_medicalcamp_alter_contactus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcamp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
