# Generated by Django 5.2 on 2026-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_medicalcamp_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcamp',
            name='is_active',
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='status',
            field=models.CharField(choices=[('post', 'post'), ('draft', 'draft'), ('hold', 'hold'), ('cancelled', 'cancelled')], default='draft', max_length=10),
        ),
    ]
