# Generated by Django 5.2 on 2026-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_medicalcamp_is_active_medicalcamp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcamp',
            name='post',
            field=models.CharField(choices=[('publish', 'Publish'), ('hold', 'Hold')], default='hold', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='camp_images/'),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
    ]
